### PR TITLE
Renaming file names for right ordered display

### PR DESCRIPTION
**Pull request by naveenprasathc**
File names from day 1 to day 9 are changed for right ordered display

### CODE REVIEW

**Comment by naveenprasathc** [comment]
image

**Comment by naveenprasathc** [comment]
day-70 thread synchronization needs to be in right place @mohitmishra786

**Comment by mohitmishra786** [comment]
@naveenprasathc i don't see any need to change for day 70, as day70 is the bonus day that I will add later
also 071 won't be looking good

**Comment by mohitmishra786** [comment]
did you tried running the change in local and see whether it is reflecting correcting now?
because after the recent change (PR done by you), it is still not changed correctly
image


if possible can you run it in local and share the image of how it is now looking

**Comment by mohitmishra786** [comment]
do lemme know if you need any help in running it

**Comment by naveenprasathc** [comment]
> @naveenprasathc i don't see any need to change for day 70, as day70 is the bonus day that I will add later also 071 won't be looking good

@mohitmishra786 sure, then i will change it

**Comment by naveenprasathc** [comment]
> do lemme know if you need any help in running it

**Comment by mohitmishra786** [comment]
you have to updated config file also, but I don't think so you need to update that stuff, you can use the same as it is

to run it is local, once you have jekyll setup done (ruby etc) then you can run directly `bundle exec jekyll serve`

**Comment by naveenprasathc** [comment]
it looks fine in the web. 
comparing mine and yours
so if you merge it, it will reflect @mohitmishra786 
image

**Pull request merged**
